
version: '{branch}-{build}'

image: Visual Studio 2017

install:
  - "SET PATH=C:\\Python33-x64;C:\\Python33-x64\\Scripts;%PATH%"
  - "python --version"
  - "pip install tox==2.1.1 virtualenv==13.1.2"

# Build the binary after tests
build: false

test_script:
  - ps: ".\\script\\build\\windows.ps1"

artifacts:
  - path: .\dist\docker-compose-Windows-x86_64.exe
    name: "Compose Windows binary"

deploy:
  - provider: Environment
    name: master-builds
    on:
      branch: master
